# Problem 1 

In [3]:
# 1 - numpy kütüphanesini import edin
import numpy as np

# 2 - 5 elemanlı bir numpy array oluşturun
a = np.array([12, 9, 4, 6, 78])

# 3 - Oluşturduğunuz arrayi küçükten büyüğe sıralayın.
print (np.sort(a))

[ 4  6  9 12 78]


# Problem 2

In [31]:
import numpy as np
import random

# 1- (10,15,30,45,60) değerlerine sahip numpy dizisi oluşturunuz.
a = np.array ([10, 15, 30, 45, 60])

# 2- (5-15) arasındaki sayılarla numpy dizisi oluşturunuz.
b = np.arange (5, 15) 
print (b)

# 3- (50-100) arasında 5'er 5'er artarak numpy dizisi oluşturunuz.
c = np.arange (50, 100, 5)
print (c)
print ("\n")

# 4- 10 elemanlı sıfırlardan oluşan bir dizi oluşturunuz.
d = np.zeros(10)
print (d)

# 5- 10 elemanlı birlerden oluşan bir dizi oluşturunuz.
w = np.ones (10)
print (w)
print ("\n")

# 6- (0-100) arasında eşit aralıklı 5 sayı üretin.
r = np.linspace (0, 100, 5)
print (r)

# 7- (10-30) arasında rastgele 5 tane tamsayı üretin.
n = np.random.randint (10, 30, 5)
print (n)
print ("\n")

# 8- [-1 ile 1] arasında 10 adet sayı üretin.
m = np.linspace(-1, 1, 10)
print (m)
print ("\n")

# 9- (3x5) boyutlarında (10-50) arasında rastgele bir matris oluşturunuz.
y = np.random.randint (10, 50, size = [3, 5])
print (y)

# 10- Üretilen matrisin satır ve sütun sayıları toplamlarını hesaplayınız ?
satir_toplamlari = np.sum(y, axis=1)  
sutun_toplamlari = np.sum(y, axis=0)  
print("Satır toplamları:", satir_toplamlari)
print("Sütun toplamları:", sutun_toplamlari)

# 11- Üretilen matrisin en büyük, en küçük ve ortalaması nedir ?
max_deger = np.max(y)
min_deger = np.min(y)
ortalama = np.mean(y)
print("En büyük değer:", max_deger)
print("En küçük değer:", min_deger)
print("Ortalama:", ortalama)

# 12- Üretilen matrisin en büyük değerinin indeksi kaçtır ?
max_index = np.unravel_index(np.argmax(y), y.shape)
print("En büyük değerin indeksi (satır, sütun):", max_index)

# 13- (10-20) arasındaki sayıları içeren dizinin ilk 3 elemanını seçiniz.
p = np.arange (10, 20)
print (p[0:3])

# 14- Üretilen dizinin elemanlarını tersten yazdırın.
print (p[::-1])
print("\n")

# 15- Üretilen matrisin ilk satırını seçiniz.
print (y[0,:])

# 16- Üretilen matrisin 2.satır 3.sütundaki elemanı hangisidir ?
print (y [2,3])

# 17- Üretilen matrisin tüm satırlardaki ilk elemanı seçiniz.
print (y [:,0])

# 18- Üretilen matrisin her bir elemanının karesini alınız.
kare = y ** 2
print("Her elemanın karesi:\n", kare)

# 19- Üretilen matris elemanlarının hangisi pozitif çift sayıdır ? Aralığı (-50,+50) arasında yapınız.
ciftler = y[(y % 2 == 0)]
print("Pozitif çift sayılar:", ciftler)

[ 5  6  7  8  9 10 11 12 13 14]
[50 55 60 65 70 75 80 85 90 95]


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


[  0.  25.  50.  75. 100.]
[11 22 20 18 24]


[-1.         -0.77777778 -0.55555556 -0.33333333 -0.11111111  0.11111111
  0.33333333  0.55555556  0.77777778  1.        ]


[[34 41 20 20 20]
 [17 36 35 33 29]
 [47 20 48 31 40]]
Satır toplamları: [135 150 186]
Sütun toplamları: [ 98  97 103  84  89]
En büyük değer: 48
En küçük değer: 17
Ortalama: 31.4
En büyük değerin indeksi (satır, sütun): (np.int64(2), np.int64(2))
[10 11 12]
[19 18 17 16 15 14 13 12 11 10]


[34 41 20 20 20]
31
[34 17 47]
Her elemanın karesi:
 [[1156 1681  400  400  400]
 [ 289 1296 1225 1089  841]
 [2209  400 2304  961 1600]]
Pozitif çift sayılar: [34 20 20 20 36 20 48 40]
