# Problem 1

In [36]:
# 1 - numpy kütüphanesini import edin
import numpy as np 

# 2 - 0 ile 10 arasında 5 sayıdan oluşan matris üretin
import random
f = np.random.randint (0, 10, 5)
print(f)

# 3 - matris'in boyutunu öğrenin
print(f.shape)

# 4 - matris'i yeniden boyutlandırın
multi = f.reshape (5 ,1)
print (multi)

# 5 - matris'in boyut sayısını öğrenin
print(multi.ndim)

[8 4 8 4 5]
(5,)
[[8]
 [4]
 [8]
 [4]
 [5]]
2


# Problem 2

In [28]:
# 1 - 0 ile 10 arasında bulunan tek sayılardan oluşan matris üretin
a = np.arange(1, 10, 2)
print(a)

# 2 - Oluşturduğunuz matrisi parçalayın
parcalar = np.split(a, [1, 4])
print(parcalar)

# 3 - Parçalanmış matrisleri birleştirin
birlesim = np.concatenate(parcalar)
print(birlesim)


[1 3 5 7 9]
[array([1]), array([3, 5, 7]), array([9])]
[1 3 5 7 9]


# Problem 3

In [38]:
import random
# 1 - 5 ile 100 arasında ikişer ikişer atlayarak rastgele 10 sayıdan oluşan matris üretin
sayilar = np.arange(5, 100, 2)  
c = np.random.choice(sayilar, 10, replace=False)  
print(c)

# 2 - matris'in özelliklerini inceleyin
print("Matris boyutu (shape):", c.shape)
print("Matris eleman sayısı (size):", c.size)
print("Matris boyut sayısı (ndim):", c.ndim)
print("Matris veri tipi (dtype):", c.dtype)

[39  5 93 37 91 45 99 75 79 65]
Matris boyutu (shape): (10,)
Matris eleman sayısı (size): 10
Matris boyut sayısı (ndim): 1
Matris veri tipi (dtype): int64
